    - name: 
      ansible.builtin.command: dnf module disable nodejs -y # Disable the Node.js module to avoid conflicts with the Node.js installation from the NodeSource repository
    
    - name: enable nodejs 20 version # Enable the Node.js 20 in server to ensure that the correct version of Node.js is installed for the application
      ansible.builtin.command: dnf module enable nodejs:20 -y 
    
    - name: insall nodejs # Install Node.js and npm using the package manager
      ansible.builtin.package:
        name: nodejs
        state: installed

    - name: Add User called Expense # Create a new user named 'expense' on the web server to run the application with appropriate permissions
      ansible.builtin.user:
        name: expense
        state: present

    - name: Create a directory for the application # Create a directory for the application and set ownership to the 'expense' user
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download the application code using link # Download the application code from the specified URL and save it to the /app directory
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip
    
    - name: Unzip the application code # Unzip the downloaded application code in the /app directory
      ansible.builtin.unarchive:
        src: /tmp/backend.zip
        dest: /app
        remote_src: yes

    - name: Install application dependencies # Install the application dependencies using npm in the /app directory
      community.general.npm:
        path: /app
        state: present

    - name: setup new service for the application (created new service already) # Create a new systemd service file for the application to manage it as a service
      ansible.builtin.template: # Will search for the backend.service file in the templates directory of the role and copy it to the specified destination on the server
        src: backend.service.j2
        dest: /etc/systemd/system/backend.service

    - name: start and enable the application service # Start and enable the application service to ensure it runs on boot
      ansible.builtin.service:
        name: backend
        state: started
        enabled: yes

    - name: install Mysql libraries # Install the necessary MySQL client libraries for Python to allow the application to connect to the MySQL database
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: pip3.9 # Use pip3.9 to ensure compatibility with Python 3.9
      loop:
        - cryptography # Required for PyMySQL
        - PyMySQL # MySQL client library for Python

    - name: Install Mysql client # Install the MySQL client package to allow the application to connect to the MySQL database
      ansible.builtin.package:
        name: mysql
        state: installed

    - name: Load schema to database # Load the database schema from the specified SQL file to set up the database for the application
      community.mysql.mysql_db:
        state: import
        name: all
        login_user: "{{ MYSQL_USER }}"
        login_password: "{{ MYSQL_PASSWORD }}"
        login_host: "{{ MYSQL_HOST }}"
        target: /app/schema/backend.sql

    - name: daemon reload # Reload the systemd daemon to recognize the new service file
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: restart the application service # Restart the application service to apply any changes and ensure it is running with the latest configuration
      ansible.builtin.service:
        name: backend
        state: restarted       
